project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto
lang: de #Sprache für die Webseite

theme: 
  - styles/phbern_ci.scss # alle Stylesheets
  
date-format: "DD.MM.YYYY" # übliche Daten in der Schweiz

bibliography:     # Liste mite allen Bibliographiedatei
  - bibliographien/bibliographie_richard.bib
  - bibliographien/bib_conrardy_full.bib
csl: bibliographien/apa7.csl          # Zitierstil, wird automatisch angewandt

link-external-newwindow: true  # damit Präsentationen in neuem Tab geöffnet werden.
fig-align: center # Bilder werden zentriert, funktioniert nicht immer



website:  # Menüs für die Webseite
  favicon: images/logo.png
  search: true
  navbar:
    logo: "images/logo.png"
    background: white
    tools:
      - icon: github
        href: https://github.com/PHBern-RConrardy/gitgud
    left:
      - text: Übersicht
        icon: binoculars-fill
        menu:
          - text: Jahresplanungen
            href: strukturen/jahresplanungen.qmd
            icon: calendar-week-fill
          - text: Fachzusammenhänge
            href: strukturen/zusammenhaenge.qmd
            icon: diagram-2-fill
      - text: Zahl
        href: mathematik/zahl/010.qmd
        icon: 0-square-fill
      - text: Variable
        href: mathematik/variable/010.qmd
        icon: box-seam-fill
      - text: Form
        href: mathematik/form/010.qmd
        icon: hexagon-fill
      - text: Raum
        href: mathematik/raum/010.qmd
        icon: boxes
      - text: Funktionen
        href: mathematik/funktionen/010.qmd
        icon: gear-wide-connected
      - text: Daten und Zufall
        href: mathematik/daten_und_zufall/010.qmd
        icon: dice-5-fill
      
  page-footer: # Fusszeile
    center: 
      - text: "Impressum"
        href: footer/impressum.qmd
      - text: "Disclaimer"
        href: footer/disclaimer.qmd 
      - text: "Kontakt"
        href: https://www.phbern.ch/ueber-die-phbern/personen/richard-conrardy  
    left: 
      - text: "PHBern"
        href: https://www.phbern.ch/
    right: 
      - text: <small>Dieses Produkt ist in einem Kontext des Lernens an der PHBern entstanden.</small>
    background: $schwarz1
    foreground: $schwarz4

format:
  html: # Einstellungen nur für Webseiten
    toc: true
    toc-expand: true
    toc-location: right
    toc-depth: 2
    license: "CC BY-SA"
    page-layout: article
    title-block-banner: true
    mermaid:
      theme: neutral
    
      
  revealjs: # Einträge nur für Präsentationen
    toc: true
    slide-number: false
    chalkboard: true
    toc-title: "Inhalt"
    footer: "[PHBern, Institut Sekundarstufe 1,](https://www.phbern.ch/studium/sekundarstufe-i)  Richard Conrardy, Dozent"
    title-slide-attributes: 
      data-background-image: "images/logo cc-by-sa.svg"
      data-background-size: 12%
      data-background-position: 94% 99%
    fig-align: center
    scrollable: true
    logo: images/logo.png
    hide-inactive-cursor: true
    mermaid:
      theme: neutral
    author:   # Autoren welche automatisch gesetzt werden, falls nichts anderes angegeben wird
      - name: Richard Conrardy
        orcid: 0009-0004-2063-6898
        id: 00383195
        email: richard.conrardy@phbern.ch
        url: https://www.phbern.ch/ueber-die-phbern/personen/richard-conrardy
        affiliations:
        - name: University of Teacher Education Bern
          address: Länggassstrasse 35
          city: Bern
          postal-code: 3012
          url: https://www.phbern.ch
          department: Institut Sekundarstufe I
          ror: https://ror.org/05jf1ma54
